export const trickData = [
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Kickflip"},
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Heelflip"},
    {stance:"Regular",  shuv:"Bs",      shuvRotation:"360", flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"360 flip"},
    {stance:"Nollie",   shuv:"Fs",      shuvRotation:"180", flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Nollie Inward Heel"},
    {stance:"Fakie",    shuv:"Fs",      shuvRotation:"180", flip:"Heelflip",    flipAmount:"1",     spin:"Fs",      spinRotation:"180", trickName:"Rick Flip / Fakie Big Heel"},
    {stance:"Regular",  shuv:"Bs",      shuvRotation:"180", flip:"Kickflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"Bigflip"},
    {stance:"Nollie",   shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Nollie Flip"},
    {stance:"Nollie",   shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Nollie Heel"},
    {stance:"Nollie",   shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"Nollie Bs Heel"},
    {stance:"Fakie",    shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Fakie Flip"},
    {stance:"Fakie",    shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Fakie Heel"},
    {stance:"Fakie",    shuv:"Bs",      shuvRotation:"180", flip:"None",        flipAmount:"0",     spin:"Bs",      spinRotation:"180", trickName:"Fakie Bigspin"},
    {stance:"Fakie",    shuv:"Fs",      shuvRotation:"180", flip:"None",        flipAmount:"0",     spin:"Fs",      spinRotation:"180", trickName:"Fakie Fs Bigspin"},
    {stance:"Switch",   shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Switch Flip"},
    {stance:"Switch",   shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Switch Heel"},
    {stance:"Switch",   shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"Fs",      spinRotation:"180", trickName:"Switch Fs Flip"},
    {stance:"Switch",   shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"Switch Bs Flip"},
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"Bs Flip"},
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"Fs",      spinRotation:"180", trickName:"Fs Flip"},
    {stance:"Regular",  shuv:"Fs",      shuvRotation:"180", flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Hardflip"},
    {stance:"Switch",   shuv:"Bs",      shuvRotation:"180", flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Switch Varial"},
    {stance:"Regular",  shub:"Bs",      shuvRotaiton:"180", flip:"Kickflip",    flipAmount:"2",     spin:"None",    spinRotation:"0",   trickName:"Nightmare Flip"},
]