export const trickData = [
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Ollie"},
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Fs",    spinRotation:"180",   trickName:"Fs 180"},
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Bs",    spinRotation:"180",   trickName:"Bs 180"},
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Fs",    spinRotation:"360",   trickName:"Fs 360"},
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Bs",    spinRotation:"360",   trickName:"Bs 360"},
    {stance:"Regular",  shuv:"Bs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Pop Shuv"},
    {stance:"Regular",  shuv:"Fs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Fs Shuv"},
    {stance:"Regular",  shuv:"Bs",    shuvRotation:"360",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"3 Shuv"},
    {stance:"Regular",  shuv:"Fs",    shuvRotation:"360",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Fs 3 Shuv"},
    {stance:"Regular",  shuv:"Bs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"Bs",    spinRotation:"180",   trickName:"Bigspin"},
    {stance:"Regular",  shuv:"Fs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"Fs",    spinRotation:"180",   trickName:"Fs Bigspin"},
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Kickflip"},
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Heelflip"},
    {stance:"Regular",  shuv:"Bs",    shuvRotation:"180",   flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Varial Flip"},
    {stance:"Regular",  shuv:"Fs",    shuvRotation:"180",   flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Varial Heel"},
    {stance:"Regular",  shuv:"Bs",      shuvRotation:"360", flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Tre"},
    {stance:"Regular",  shuv:"Fs",      shuvRotation:"360", flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Lazer"},
    {stance:"Regular",  shuv:"Bs",      shuvRotation:"180", flip:"Kickflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"BigFlip"},
    {stance:"Regular",  shuv:"Fs",      shuvRotation:"180", flip:"Heelflip",    flipAmount:"1",     spin:"Fs",      spinRotation:"180", trickName:"BigHeel"},
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"Bs Flip"},
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"Fs",      spinRotation:"180", trickName:"Fs Flip"},
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"Bs Heel"},
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"Fs",      spinRotation:"180", trickName:"Fs Heel"},
    {stance:"Regular",  shuv:"Fs",      shuvRotation:"180", flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Hardflip"},
    {stance:"Regular",  shuv:"Bs",      shuvRotation:"180", flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Inward Heel"},

    {stance:"Regular",  shuv:"Bs",      shuvRotaiton:"180", flip:"Kickflip",    flipAmount:"2",     spin:"None",    spinRotation:"0",   trickName:"Nightmare Flip"},
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"2",     spin:"None",    spinRotation:"0",   trickName:"Double Flip"},
    {stance:"Regular",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"2",     spin:"None",    spinRotation:"0",   trickName:"Double Heel"},
    {stance:"Regular",  shuv:"Bs",      shuvRotation:"540", flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"540 Flip"},

    {stance:"Nollie",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Nollie"},
    {stance:"Nollie",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Fs",    spinRotation:"180",   trickName:"Nollie Fs 180"},
    {stance:"Nollie",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Bs",    spinRotation:"180",   trickName:"Nollie Bs 180"},
    {stance:"Nollie",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Fs",    spinRotation:"360",   trickName:"Nollie Fs 360"},
    {stance:"Nollie",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Bs",    spinRotation:"360",   trickName:"Nollie Bs 360"},
    {stance:"Nollie",  shuv:"Bs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Nollie Bs Shuv"},
    {stance:"Nollie",  shuv:"Fs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Nollie Fs Shuv"},
    {stance:"Nollie",  shuv:"Bs",    shuvRotation:"360",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Nollie Bs 3 Shuv"},
    {stance:"Nollie",  shuv:"Fs",    shuvRotation:"360",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Nollie 3 Shuv"},
    {stance:"Nollie",  shuv:"Bs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"Bs",    spinRotation:"180",   trickName:"Nollie Bigspin"},
    {stance:"Nollie",  shuv:"Fs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"Fs",    spinRotation:"180",   trickName:"Nollie Fs Bigspin"},
    {stance:"Nollie",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Nollie Flip"},
    {stance:"Nollie",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Nollie Heel"},
    {stance:"Nollie",  shuv:"Fs",    shuvRotation:"180",   flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Nollie Varial Flip"},
    {stance:"Nollie",  shuv:"Bs",    shuvRotation:"180",   flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Nollie Varial Heel"},
    {stance:"Nollie",  shuv:"Fs",      shuvRotation:"360", flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Nollie Tre"},
    {stance:"Nollie",  shuv:"Bs",      shuvRotation:"360", flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Nollie Lazer"},
    {stance:"Nollie",  shuv:"Fs",      shuvRotation:"180", flip:"Kickflip",    flipAmount:"1",     spin:"Fs",      spinRotation:"180", trickName:"Nollie Bigflip"},
    {stance:"Nollie",  shuv:"Bs",      shuvRotation:"180", flip:"Heelflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"Nollie BigHeel"},
    {stance:"Nollie",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"Nollie Bs Flip"},
    {stance:"Nollie",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"Fs",      spinRotation:"180", trickName:"Nollie Fs Flip"},
    {stance:"Nollie",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"Nollie Bs Heel"},
    {stance:"Nollie",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"Fs",      spinRotation:"180", trickName:"Nollie Fs Heel"},
    {stance:"Nollie",  shuv:"Bs",      shuvRotation:"180", flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Nollie Hardflip"},
    {stance:"Nollie",  shuv:"Fs",      shuvRotation:"180", flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Nollie Inward Heel"},

    {stance:"Nollie",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"2",     spin:"None",    spinRotation:"0",   trickName:"Nollie Double Flip"},
    {stance:"Nollie",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"2",     spin:"None",    spinRotation:"0",   trickName:"Nollie Double Heel"},

    {stance:"Nollie",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"3",     spin:"None",    spinRotation:"0",   trickName:"Nollie Triple Flip"},
    {stance:"Nollie",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"3",     spin:"None",    spinRotation:"0",   trickName:"Nollie Triple Heel"},

    {stance:"Fakie",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Fakie Ollie"},
    {stance:"Fakie",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Bs",    spinRotation:"180",   trickName:"Half Cab"},
    {stance:"Fakie",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Bs",    spinRotation:"360",   trickName:"Full Cab"},
    {stance:"Fakie",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Fs",    spinRotation:"180",   trickName:"Fakie Fs 180"},
    {stance:"Fakie",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Fs",    spinRotation:"360",   trickName:"Fakie Fs 360"},
    {stance:"Fakie",  shuv:"Bs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Fakie Shuv"},
    {stance:"Fakie",  shuv:"Fs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Fakie Fs Shuv"},
    {stance:"Fakie",  shuv:"Bs",    shuvRotation:"360",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Fakie 3 Shuv"},
    {stance:"Fakie",  shuv:"Fs",    shuvRotation:"360",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Fakie Fs 3 Shuv"},
    {stance:"Fakie",  shuv:"Bs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"Bs",    spinRotation:"180",   trickName:"Fakie Bigspin"},
    {stance:"Fakie",  shuv:"Fs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"Fs",    spinRotation:"180",   trickName:"Fakie Fs Bigspin"},
    {stance:"Fakie",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Fakie Flip"},
    {stance:"Fakie",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Fakie Heel"},
    {stance:"Fakie",  shuv:"Bs",    shuvRotation:"180",   flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Fakie Varial Flip"},
    {stance:"Fakie",  shuv:"Fs",    shuvRotation:"180",   flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Fakie Varial Heel"},
    {stance:"Fakie",  shuv:"Bs",      shuvRotation:"360", flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Fakie Tre"},
    {stance:"Fakie",  shuv:"Fs",      shuvRotation:"360", flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Fakie Lazer"},
    {stance:"Fakie",  shuv:"Bs",      shuvRotation:"180", flip:"Kickflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"Fakie BigFlip"},
    {stance:"Fakie",  shuv:"Fs",      shuvRotation:"180", flip:"Heelflip",    flipAmount:"1",     spin:"Fs",      spinRotation:"180", trickName:"Fakie BigHeel"},
    {stance:"Fakie",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"Half Cab Flip"},
    {stance:"Fakie",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"360", trickName:"Full Cab Flip"},
    {stance:"Fakie",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"Fs",      spinRotation:"180", trickName:"Fakie Fs Flip"},
    {stance:"Fakie",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"Half Cab Heel"},
    {stance:"Fakie",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"Fs",      spinRotation:"180", trickName:"Fakie Fs Heel"},
    {stance:"Fakie",  shuv:"Fs",      shuvRotation:"180", flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Fakie Hardflip"},
    {stance:"Fakie",  shuv:"Bs",      shuvRotation:"180", flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Fakie Inward Heel"},

    {stance:"Fakie",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"2",     spin:"None",    spinRotation:"0",   trickName:"Fakie Double Flip"},
    {stance:"Fakie",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"2",     spin:"None",    spinRotation:"0",   trickName:"Fakie Double Heel"},

    {stance:"Switch",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Switch Ollie"},
    {stance:"Switch",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Fs",    spinRotation:"180",   trickName:"Switch Fs 180"},
    {stance:"Switch",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Bs",    spinRotation:"180",   trickName:"Switch Bs 180"},
    {stance:"Switch",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Fs",    spinRotation:"360",   trickName:"Switch Fs 360"},
    {stance:"Switch",  shuv:"None",    shuvRotation:"0",   flip:"None",    flipAmount:"0",     spin:"Bs",    spinRotation:"360",   trickName:"Switch Bs 360"},
    {stance:"Switch",  shuv:"Bs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Switch Shuv"},
    {stance:"Switch",  shuv:"Fs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Switch Fs Shuv"},
    {stance:"Switch",  shuv:"Bs",    shuvRotation:"360",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Switch 3 Shuv"},
    {stance:"Switch",  shuv:"Fs",    shuvRotation:"360",   flip:"None",    flipAmount:"0",     spin:"None",    spinRotation:"0",   trickName:"Switch Fs 3 Shuv"},
    {stance:"Switch",  shuv:"Bs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"Bs",    spinRotation:"180",   trickName:"Switch Bigspin"},
    {stance:"Switch",  shuv:"Fs",    shuvRotation:"180",   flip:"None",    flipAmount:"0",     spin:"Fs",    spinRotation:"180",   trickName:"Switch Fs Bigspin"},
    {stance:"Switch",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Switch Flip"},
    {stance:"Switch",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Switch Heel"},
    {stance:"Switch",  shuv:"Bs",    shuvRotation:"180",   flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Switch Varial Flip"},
    {stance:"Switch",  shuv:"Fs",    shuvRotation:"180",   flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Switch Varial Heel"},
    {stance:"Switch",  shuv:"Bs",      shuvRotation:"360", flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Switch Tre"},
    {stance:"Switch",  shuv:"Fs",      shuvRotation:"360", flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Switch Lazer"},
    {stance:"Switch",  shuv:"Bs",      shuvRotation:"180", flip:"Kickflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"Switch Bigflip"},
    {stance:"Switch",  shuv:"Fs",      shuvRotation:"180", flip:"Heelflip",    flipAmount:"1",     spin:"Fs",      spinRotation:"180", trickName:"Switch BigHeel"},
    {stance:"Switch",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"Switch Bs Flip"},
    {stance:"Switch",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"1",     spin:"Fs",      spinRotation:"180", trickName:"Switch Fs Flip"},
    {stance:"Switch",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"Bs",      spinRotation:"180", trickName:"Switch Bs Heel"},
    {stance:"Switch",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"1",     spin:"Fs",      spinRotation:"180", trickName:"Switch Fs Heel"},
    {stance:"Switch",  shuv:"Fs",      shuvRotation:"180", flip:"Kickflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Switch Hardflip"},
    {stance:"Switch",  shuv:"Bs",      shuvRotation:"360", flip:"Kickflip",    flipAmount:"2",     spin:"None",    spinRotation:"0",   trickName:"Switch Double Tre"},
    {stance:"Switch",  shuv:"Bs",      shuvRotation:"180", flip:"Heelflip",    flipAmount:"1",     spin:"None",    spinRotation:"0",   trickName:"Switch Inward Heel"},
    
    {stance:"Switch",  shuv:"None",    shuvRotation:"0",   flip:"Kickflip",    flipAmount:"2",     spin:"None",    spinRotation:"0",   trickName:"Switch Double Flip"},
    {stance:"Switch",  shuv:"None",    shuvRotation:"0",   flip:"Heelflip",    flipAmount:"2",     spin:"None",    spinRotation:"0",   trickName:"Switch Double Heel"},
]