export const tricks = [
    { value: 0, label: "Kickflip" },
    { value: 1, label: "Heelflip" },
    { value: 2, label: "360 Flip" },
    { value: 3, label: "Nollie Inward Heel" },
    { value: 4, label: "Rick Flip / Fakie Big Heel" },
    { value: 5, label: "Bigflip" },
    { value: 6, label: "Nollie Flip" },
    { value: 7, label: "Nollie Heel" },
    { value: 8, label: "Nollie Bs Heel" },
    { value: 9, label: "Fakie Flip" },
    { value: 10, label: "Fakie Heel" },
    { value: 11, label: "Fakie Bigspin" },
    { value: 12, label: "Fakie Fs Bigspin" },
    { value: 13, label: "Switch Flip" },
    { value: 14, label: "Switch Heel" },
    { value: 15, label: "Switch Fs Flip" },
    { value: 16, label: "Switch Bs Flip" },

]